const colors = {
  light: {
    text: "#0a1628",
    tint: "#3a7aff",
    background: "#f0f4ff",
    foreground: "#0a1628",
    card: "#ffffff",
    cardForeground: "#0a1628",
    primary: "#3a7aff",
    primaryForeground: "#ffffff",
    secondary: "#e8efff",
    secondaryForeground: "#0a1628",
    muted: "#f5f7fc",
    mutedForeground: "#5a7a9e",
    accent: "#dde5f5",
    accentForeground: "#0a1628",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#dde5f0",
    input: "#f0f4ff",
    success: "#16a34a",
    successForeground: "#ffffff",
    gold: "#d97706",
    deepBlue: "#0a1628",
    sand: "#f0f4ff",
    coral: "#3a7aff",
  },
  dark: {
    text: "#e8f0ff",
    tint: "#4d8eff",
    background: "#070f1e",
    foreground: "#e8f0ff",
    card: "#0d1f3c",
    cardForeground: "#e8f0ff",
    primary: "#4d8eff",
    primaryForeground: "#ffffff",
    secondary: "#1a3a6b",
    secondaryForeground: "#e8f0ff",
    muted: "#0f1e38",
    mutedForeground: "#7a9fc4",
    accent: "#1e3d78",
    accentForeground: "#e8f0ff",
    destructive: "#e04444",
    destructiveForeground: "#ffffff",
    border: "#1c3056",
    input: "#0f1e38",
    success: "#22c55e",
    successForeground: "#ffffff",
    gold: "#f59e0b",
    deepBlue: "#0a1628",
    sand: "#0d1f3c",
    coral: "#4a90e2",
  },
  radius: 14,
};

export default colors;
