const colors = {
  light: {
    text: "#0d2b2a",
    tint: "#0abab5",
    background: "#ffffff",
    foreground: "#0d2b2a",
    card: "#f5fefe",
    cardForeground: "#0d2b2a",
    primary: "#0abab5",
    primaryForeground: "#ffffff",
    secondary: "#81d8d0",
    secondaryForeground: "#0d2b2a",
    muted: "#e8f8f8",
    mutedForeground: "#4a8a87",
    accent: "#b2ebea",
    accentForeground: "#0d2b2a",
    destructive: "#e04444",
    destructiveForeground: "#ffffff",
    border: "#c8eceb",
    input: "#e8f8f8",
    success: "#0abab5",
    successForeground: "#ffffff",
    gold: "#0abab5",
    deepBlue: "#0abab5",
    sand: "#e8f8f8",
    coral: "#81d8d0",
  },
  radius: 14,
};

export default colors;
